lc-10: solution.c Makefile
	gcc -g -O0 -o lc-10 solution.c -std=c23 -Wall -Wpedantic -fsanitize=undefined,address,leak,pointer-compare,pointer-subtract

lc-10.nosan: solution.c Makefile
	gcc -g -O0 -o lc-10.nosan solution.c -std=c23 -Wall -Wpedantic
